import { defineType, defineField } from 'sanity'
import { withAIGeneration } from '../utils/ai-generation'

export const categoryBlogType = defineType({
  type: 'document',
  name: 'categoryBlog',
  title: 'Category',
  description: '',
  fields: [
    defineField({name: 'title', type: 'string', title: 'Title', hidden: false}),
    defineField({
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      hidden: false,
      description:
        'The slug will be used for URL paths or for #anchor tags, depending on the configuration of your site.',
      options: {source: 'title'},
    }),
    defineField({
      name: 'hero',
      type: 'reference',
      title: 'Hero',
      hidden: false,
      description: 'Choose the Hero item that will appear at the top of the page.',
      to: [{type: 'hero'}],
    }),
    defineField({
      name: 'body',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 1', value: 'h1'},
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Code', value: 'code'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'section'},
                  {type: 'card'},
                  {type: 'link'},
                  {type: 'collection'},
                  {type: 'contentful_text'},
                  {type: 'page'},
                  {type: 'hero'},
                  {type: 'navigationItem'},
                  {type: 'site'},
                  {type: 'header'},
                  {type: 'moduleIntegration'},
                  {type: 'media'},
                  {type: 'person'},
                  {type: 'categoryBlog'},
                  {type: 'template'},
                  {type: 'settings'},
                  {type: 'contentful_block'},
                  {type: 'footer'},
                  {type: 'collectionDynamic'},
                  {type: 'elementForm'},
                  {type: 'elementVideo'},
                  {type: 'collectionExpandableItem'},
                  {type: 'collectionExpandable'},
                  {type: 'blog'},
                  {type: 'siteRedirect'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
          of: [
            {
              type: 'reference',
              title: 'Reference',
              to: [
                {type: 'section'},
                {type: 'card'},
                {type: 'link'},
                {type: 'collection'},
                {type: 'contentful_text'},
                {type: 'page'},
                {type: 'hero'},
                {type: 'navigationItem'},
                {type: 'site'},
                {type: 'header'},
                {type: 'moduleIntegration'},
                {type: 'media'},
                {type: 'person'},
                {type: 'categoryBlog'},
                {type: 'template'},
                {type: 'settings'},
                {type: 'contentful_block'},
                {type: 'footer'},
                {type: 'collectionDynamic'},
                {type: 'elementForm'},
                {type: 'elementVideo'},
                {type: 'collectionExpandableItem'},
                {type: 'collectionExpandable'},
                {type: 'blog'},
                {type: 'siteRedirect'},
              ],
            },
          ],
        },
        {
          type: 'reference',
          title: 'Reference',
          to: [
            {type: 'section'},
            {type: 'card'},
            {type: 'link'},
            {type: 'collection'},
            {type: 'contentful_text'},
            {type: 'page'},
            {type: 'hero'},
            {type: 'navigationItem'},
            {type: 'site'},
            {type: 'header'},
            {type: 'moduleIntegration'},
            {type: 'media'},
            {type: 'person'},
            {type: 'categoryBlog'},
            {type: 'template'},
            {type: 'settings'},
            {type: 'contentful_block'},
            {type: 'footer'},
            {type: 'collectionDynamic'},
            {type: 'elementForm'},
            {type: 'elementVideo'},
            {type: 'collectionExpandableItem'},
            {type: 'collectionExpandable'},
            {type: 'blog'},
            {type: 'siteRedirect'},
          ],
        },
        {type: 'image'},
        {type: 'file'},
        {type: 'break'},
      ],
      title: 'Body',
      hidden: false,
    }),
    withAIGeneration(
      defineField({
        name: 'promoSummary',
        type: 'text',
        title: 'Promo Summary',
        hidden: false,
        description:
          '[Optional] When promoting this page, this summary may be shown dynamically rendered cards, listing pages, etc.)',
      }),
    ),
    defineField({
      name: 'promoImage',
      type: 'image',
      title: 'Promo Image',
      hidden: false,
      description:
        '[Optional] When promoting this page, this image may be shown dynamically rendered cards, listing pages, etc.)',
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'title'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
})
