import { defineType, defineField } from 'sanity'
import { withAIGeneration } from '../utils/ai-generation'
import { validateIn } from '../utils/validation'

export const contentful_textType = defineType({
  type: 'document',
  name: 'contentful_text',
  title: 'Element - Text',
  description: '',
  fields: [
    withAIGeneration(
      defineField({name: 'internalTitle', type: 'string', title: 'Internal Title', hidden: false}),
    ),
    defineField({
      name: 'variant',
      type: 'string',
      title: 'Layout Style',
      hidden: false,
      description: 'The Variant determines the style or the format the Text item. ',

      initialValue: 'default',
      validation: (Rule) => Rule.custom((value) => validateIn(['default', 'Intro Text'], value)),
      options: {list: ['default', 'Intro Text'], layout: 'dropdown'},
    }),
    withAIGeneration(
      defineField({
        name: 'overline',
        type: 'string',
        title: 'Overline',
        hidden: false,
        description: '[Optional] This field will be displayed above the Title.',
      }),
    ),
    withAIGeneration(defineField({name: 'title', type: 'string', title: 'Title', hidden: false})),
    withAIGeneration(
      defineField({
        name: 'subtitle',
        type: 'string',
        title: 'Subtitle',
        hidden: false,
        description: '[Optional] This field will be displayed below the Title.',
      }),
    ),
    defineField({
      name: 'body',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 1', value: 'h1'},
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Code', value: 'code'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'section'},
                  {type: 'card'},
                  {type: 'link'},
                  {type: 'collection'},
                  {type: 'contentful_text'},
                  {type: 'page'},
                  {type: 'hero'},
                  {type: 'navigationItem'},
                  {type: 'site'},
                  {type: 'header'},
                  {type: 'moduleIntegration'},
                  {type: 'media'},
                  {type: 'person'},
                  {type: 'categoryBlog'},
                  {type: 'template'},
                  {type: 'settings'},
                  {type: 'contentful_block'},
                  {type: 'footer'},
                  {type: 'collectionDynamic'},
                  {type: 'elementForm'},
                  {type: 'elementVideo'},
                  {type: 'collectionExpandableItem'},
                  {type: 'collectionExpandable'},
                  {type: 'blog'},
                  {type: 'siteRedirect'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
          of: [
            {
              type: 'reference',
              title: 'Reference',
              to: [
                {type: 'section'},
                {type: 'card'},
                {type: 'link'},
                {type: 'collection'},
                {type: 'contentful_text'},
                {type: 'page'},
                {type: 'hero'},
                {type: 'navigationItem'},
                {type: 'site'},
                {type: 'header'},
                {type: 'moduleIntegration'},
                {type: 'media'},
                {type: 'person'},
                {type: 'categoryBlog'},
                {type: 'template'},
                {type: 'settings'},
                {type: 'contentful_block'},
                {type: 'footer'},
                {type: 'collectionDynamic'},
                {type: 'elementForm'},
                {type: 'elementVideo'},
                {type: 'collectionExpandableItem'},
                {type: 'collectionExpandable'},
                {type: 'blog'},
                {type: 'siteRedirect'},
              ],
            },
          ],
        },
        {
          type: 'reference',
          title: 'Reference',
          to: [
            {type: 'section'},
            {type: 'card'},
            {type: 'link'},
            {type: 'collection'},
            {type: 'contentful_text'},
            {type: 'page'},
            {type: 'hero'},
            {type: 'navigationItem'},
            {type: 'site'},
            {type: 'header'},
            {type: 'moduleIntegration'},
            {type: 'media'},
            {type: 'person'},
            {type: 'categoryBlog'},
            {type: 'template'},
            {type: 'settings'},
            {type: 'contentful_block'},
            {type: 'footer'},
            {type: 'collectionDynamic'},
            {type: 'elementForm'},
            {type: 'elementVideo'},
            {type: 'collectionExpandableItem'},
            {type: 'collectionExpandable'},
            {type: 'blog'},
            {type: 'siteRedirect'},
          ],
        },
        {type: 'image'},
        {type: 'file'},
        {type: 'break'},
      ],
      title: 'Body',
      hidden: false,
    }),
    defineField({
      name: 'align',
      type: 'string',
      title: 'Text Alignment',
      hidden: false,
      description: 'Choose alignment of the text (e.g. left, right, center).',

      initialValue: 'Default',
      validation: (Rule) =>
        Rule.required().custom((value) =>
          validateIn(['Default', 'Left', 'Center', 'Right', 'Justified'], value),
        ),
      options: {list: ['Default', 'Left', 'Center', 'Right', 'Justified'], layout: 'dropdown'},
    }),
    defineField({
      name: 'backgroundColor',
      type: 'string',
      title: 'Background Color',
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) => validateIn(['Transparent', 'Black', 'White', 'Navy'], value)),
      options: {list: ['Transparent', 'Black', 'White', 'Navy'], layout: 'dropdown'},
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'internalTitle'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
})
