import { defineType, defineField } from 'sanity'
import { withAIGeneration } from '../utils/ai-generation'

export const personType = defineType({
  type: 'document',
  name: 'person',
  title: 'Page - Person',
  description: '',
  fields: [
    defineField({name: 'name', type: 'string', title: 'Name', hidden: false}),
    defineField({
      name: 'parentPage',
      type: 'reference',
      title: 'Parent Page',
      hidden: false,
      description:
        'This parent page will be used to build the path of the final URL for this page. Choose the page that resides directly above this page in the site hierarchy. If this is a "first-level" page, choose the Homepage. ',
      to: [{type: 'page'}],
    }),
    defineField({
      name: 'slug',
      type: 'string',
      title: 'Slug',
      hidden: false,
      validation: (Rule) =>
        (Rule.required() as any).regex(/^([^\/][a-zA-Z0-9_\-\/]*[^\/])|(\/)$/, {invert: false}),
    }),
    defineField({
      name: 'jobTitle',
      type: 'string',
      title: 'Job Title',
      hidden: false,
      description: 'Enter the job title or company name of the person.',
    }),
    defineField({
      name: 'education',
      type: 'array',
      of: [{type: 'string'}],
      title: 'Education',
      hidden: false,
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'previousExperiences',
      type: 'array',
      of: [{type: 'string'}],
      title: 'Previous Experiences',
      hidden: false,
      options: {layout: 'tags'},
    }),
    defineField({name: 'mainImage', type: 'image', title: 'Main Image', hidden: false}),
    defineField({name: 'rolloverImage', type: 'image', title: 'Rollover Image', hidden: false}),
    defineField({
      name: 'body',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Code', value: 'code'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'section'},
                  {type: 'card'},
                  {type: 'link'},
                  {type: 'collection'},
                  {type: 'contentful_text'},
                  {type: 'page'},
                  {type: 'hero'},
                  {type: 'navigationItem'},
                  {type: 'site'},
                  {type: 'header'},
                  {type: 'moduleIntegration'},
                  {type: 'media'},
                  {type: 'person'},
                  {type: 'categoryBlog'},
                  {type: 'template'},
                  {type: 'settings'},
                  {type: 'contentful_block'},
                  {type: 'footer'},
                  {type: 'collectionDynamic'},
                  {type: 'elementForm'},
                  {type: 'elementVideo'},
                  {type: 'collectionExpandableItem'},
                  {type: 'collectionExpandable'},
                  {type: 'blog'},
                  {type: 'siteRedirect'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
          of: [
            {
              type: 'reference',
              title: 'Reference',
              to: [
                {type: 'section'},
                {type: 'card'},
                {type: 'link'},
                {type: 'collection'},
                {type: 'contentful_text'},
                {type: 'page'},
                {type: 'hero'},
                {type: 'navigationItem'},
                {type: 'site'},
                {type: 'header'},
                {type: 'moduleIntegration'},
                {type: 'media'},
                {type: 'person'},
                {type: 'categoryBlog'},
                {type: 'template'},
                {type: 'settings'},
                {type: 'contentful_block'},
                {type: 'footer'},
                {type: 'collectionDynamic'},
                {type: 'elementForm'},
                {type: 'elementVideo'},
                {type: 'collectionExpandableItem'},
                {type: 'collectionExpandable'},
                {type: 'blog'},
                {type: 'siteRedirect'},
              ],
            },
          ],
        },
        {
          type: 'reference',
          title: 'Reference',
          to: [
            {type: 'section'},
            {type: 'card'},
            {type: 'link'},
            {type: 'collection'},
            {type: 'contentful_text'},
            {type: 'page'},
            {type: 'hero'},
            {type: 'navigationItem'},
            {type: 'site'},
            {type: 'header'},
            {type: 'moduleIntegration'},
            {type: 'media'},
            {type: 'person'},
            {type: 'categoryBlog'},
            {type: 'template'},
            {type: 'settings'},
            {type: 'contentful_block'},
            {type: 'footer'},
            {type: 'collectionDynamic'},
            {type: 'elementForm'},
            {type: 'elementVideo'},
            {type: 'collectionExpandableItem'},
            {type: 'collectionExpandable'},
            {type: 'blog'},
            {type: 'siteRedirect'},
          ],
        },
        {type: 'image'},
        {type: 'file'},
        {type: 'break'},
      ],
      title: 'Bio Details',
      hidden: false,
    }),
    defineField({
      name: 'socialLinks',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'link'}]}],
      title: 'Social Links',
      hidden: false,
    }),
    defineField({
      name: 'email',
      type: 'string',
      title: 'Email',
      hidden: false,
      validation: (Rule) => Rule.regex(/^\w[\w.-]*@([\w-]+\.)+[\w-]+$/, {invert: false}),
    }),
    withAIGeneration(
      defineField({
        name: 'promoSummary',
        type: 'text',
        title: 'Promo Summary',
        hidden: false,
        description:
          '[Optional] When promoting this page, this summary may be shown dynamically rendered cards, listing pages, etc.)',
      }),
    ),
    defineField({
      name: 'promoImage',
      type: 'image',
      title: 'Promo Image',
      hidden: false,
      description:
        '[Optional] When promoting this page, this image may be shown dynamically rendered cards, listing pages, etc.)',
    }),
    defineField({
      name: 'headerOverride',
      type: 'reference',
      title: 'Header Override',
      hidden: false,
      to: [{type: 'header'}],
    }),
    defineField({
      name: 'footerOverride',
      type: 'reference',
      title: 'Footer Override',
      hidden: false,
      to: [{type: 'footer'}],
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'name'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
})
