import { defineType, defineField } from 'sanity'
import { withAIGeneration } from '../utils/ai-generation'
import { validateIn } from '../utils/validation'

export const settingsType = defineType({
  type: 'document',
  name: 'settings',
  title: 'Site - Last Rev Settings',
  description: '',
  fields: [
    withAIGeneration(
      defineField({name: 'internalTitle', type: 'string', title: 'Internal Title', hidden: false}),
    ),
    defineField({
      name: 'settingsType',
      type: 'string',
      title: 'Settings Type',
      hidden: false,
      description: 'Choose the type of Settings this represents',
      validation: (Rule) =>
        Rule.required().custom((value) =>
          validateIn(['Live Editor Settings', 'RTE Settings', 'Template', 'FRD'], value),
        ),
      options: {
        list: ['Live Editor Settings', 'RTE Settings', 'Template', 'FRD'],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'image',
      type: 'file',
      title: 'Template Image',
      hidden: false,
      description: 'Used for Templates',
    }),
    defineField({
      name: 'content',
      type: 'reference',
      title: 'Template Content',
      hidden: false,
      description: 'Currently Used for Templates',
      to: [
        {type: 'section'},
        {type: 'card'},
        {type: 'link'},
        {type: 'collection'},
        {type: 'contentful_text'},
        {type: 'page'},
        {type: 'hero'},
        {type: 'navigationItem'},
        {type: 'site'},
        {type: 'header'},
        {type: 'moduleIntegration'},
        {type: 'media'},
        {type: 'person'},
        {type: 'categoryBlog'},
        {type: 'template'},
        {type: 'settings'},
        {type: 'contentful_block'},
        {type: 'footer'},
        {type: 'collectionDynamic'},
        {type: 'elementForm'},
        {type: 'elementVideo'},
        {type: 'collectionExpandableItem'},
        {type: 'collectionExpandable'},
        {type: 'blog'},
        {type: 'siteRedirect'},
      ],
    }),
    defineField({
      name: 'category',
      type: 'string',
      title: 'Template Category',
      hidden: false,

      initialValue: 'Used for template categorization',
    }),
    defineField({
      name: 'frdContents',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [
            {type: 'section'},
            {type: 'card'},
            {type: 'link'},
            {type: 'collection'},
            {type: 'contentful_text'},
            {type: 'page'},
            {type: 'hero'},
            {type: 'navigationItem'},
            {type: 'site'},
            {type: 'header'},
            {type: 'moduleIntegration'},
            {type: 'media'},
            {type: 'person'},
            {type: 'categoryBlog'},
            {type: 'template'},
            {type: 'settings'},
            {type: 'contentful_block'},
            {type: 'footer'},
            {type: 'collectionDynamic'},
            {type: 'elementForm'},
            {type: 'elementVideo'},
            {type: 'collectionExpandableItem'},
            {type: 'collectionExpandable'},
            {type: 'blog'},
            {type: 'siteRedirect'},
          ],
        },
      ],
      title: 'FRD Contents',
      hidden: false,
      description: 'This is used to generate the FRD Page that will be shown at /frd',
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'internalTitle'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
})
