const cspConfig = {
  defaultSrc: [
    "'self'",
    'https://*.flowise.theanswer.ai',
    'https://*.theanswer.ai',
    'localhost:8888',
    'https://*.sentry.io',
    'https://*.facebook.com',
    'vitals.vercel-insights.com',
    'https://*.hubapi.com',
    'https://*.hsforms.com',
    'https://*.hs-scripts.com',
    'https://*.hsforms.net',
    'https://*.hscollectedforms.net',
    'https://*.netlify.app',
    'https://*.googletagmanager.com',
    'https://*.google-analytics.com'
  ],
  styleSrc: [
    "'self'",
    "'unsafe-inline'",
    'https://*.sentry.io',
    'fonts.googleapis.com',
    'vitals.vercel-insights.com',
    'https://*.hs-scripts.com',
    'https://*.hsforms.net',
    'https://*.googletagmanager.com',
    'https://*.google-analytics.com'
  ],
  scriptSrc: [
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    'https://*.flowise.theanswer.ai',
    'https://*.theanswer.ai',
    'https://*.sentry.io',
    'https://*.google-analytics.com',
    'https://*.googletagmanager.com',
    'vitals.vercel-insights.com',
    'https://*.hs-analytics.net',
    'https://*.hs-banner.com',
    'https://*.hsadspixel.net',
    'https://*.hscollectedforms.net',
    'https://*.jquery.com',
    'https://*.hs-scripts.com',
    'https://*.hsforms.net',
    'https://*.hubspot.com',
    'https://js.hs-scripts.com',
    'https://js.hsforms.net',
    'https://js.hubspot.com',
    'https://netlify-cdp-loader.netlify.app',
    'https://*.netlify.app',
    'https://f.vimeocdn.com',
    'https://www.gstatic.com',
    'https://*.googleadservices.com',
    'https://*.doubleclick.net',
    'https://*.g.doubleclick.net',
    'https://*.analytics.google.com',
    'https://analytics.google.com'
  ],
  fontSrc: [
    "'self'",
    'https://*.sentry.io',
    'fonts.gstatic.com',
    'https://*.hs-scripts.com',
    'https://*.hsforms.net',
    'data:',
    'https://*.googletagmanager.com',
    'https://*.google-analytics.com'
  ],
  connectSrc: [
    'https://*.hsforms.com',
    'https://*.hsforms.net',
    'https://*.hubapi.com',
    'https://*.hs-scripts.com',
    'https://*.hscollectedforms.net',
    'https://track.hubspot.com',
    'https://*.hubspot.com',
    'https://*.hs-analytics.net',
    'https://*.hubspot.net',
    'https://*.google-analytics.com',
    'https://*.analytics.google.com',
    'https://*.doubleclick.net',
    'https://*.g.doubleclick.net'
  ],
  frameSrc: [
    "'self'",
    'lastrev.com',
    'forms.hsforms.com',
    'https://*.theanswer.ai',
    'https://*.flowise.theanswer.ai',
    'https://*.googletagmanager.com',
    'https://www.google.com',
    'https://www.youtube.com',
    'https://*.hubspot.com',
    'https://meetings.hubspot.com',
    'https://*.doubleclick.net',
    'https://*.g.doubleclick.net'
  ],
  imgSrc: [
    "'self'",
    'https://*.googletagmanager.com',
    'https://*.ctfassets.net',
    'https://images.contentful.com',
    'https://forms-na1.hsforms.com',
    'https://*.hsforms.com',
    'https://track.hubspot.com',
    'https://*.hubspot.com',
    'data:',
    'https://*.hsforms.net',
    'https://*.hs-analytics.net',
    'https://*.google.com',
    'https://*.doubleclick.net',
    'https://*.g.doubleclick.net',
    'https://*.analytics.google.com'
  ],
  mediaSrc: ['*', 'data:'],
  objectSrc: ["'none'"],
  baseUri: ["'self'"],
  formAction: ["'self'", 'https://*.hsforms.com'],
  frameAncestors: [
    "'self'",
    'https://app.contentful.com',
    'https://lastrev.com',
    'https://lr-live-editor.netlify.app',
    'https://*.theanswer.ai',
    'https://*.flowise.theanswer.ai'
  ]
};

module.exports = cspConfig;
