name: Lint Codebase
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install ESLint
        run: npm install eslint

      # This will flag all console statements as errors
      - name: Create ESLint config to disallow all console logs
        run: |
          echo 'module.exports = { rules: { "no-console": "error" } };' > eslint.config.js

      - name: Run ESLint to check for console logs
        run: |
          npx eslint '**/*' --config eslint.config.js
          rm eslint.config.js