name: Lint Codebase

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  lint:
    uses: last-rev-llc/workflows/.github/workflows/lint.yml@main